# --- font ---
font_family       FiraCode Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 13.0

# --- cursor ---
cursor                  #7e01ff
cursor_shape            beam
cursor_shape_unfocused  hollow

cursor_beam_thickness 1.0
cursor_beam_thickness 0.9
cursor_stop_blinking_after 5.0

# cursor_trail 0.5
# cursor_trail_decay 0.1 0.4
# cursor_trail_start_threshold 2

# Scrollback
scrollback_lines 4000
scrollback_indicator_opacity 0.5
wheel_scroll_multiplier 3.0

confirm_os_window_close 1

background_blur 1
#background_opacity 0.8
