# --- Launcher ---
bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod CTRL, Y, exec, $terminal "yazi"
bind = $mainMod CTRL, E, exec, $filemanager

bind = $mainMod, D, exec, pkill wofi || wofi --show drun
bind = $mainMod, V, exec, pkill wofi || cliphist-wofi | wl-copy

bind = $mainMod, N, exec, swaync-client -t

#остальной запуск
bind = $mainMod CTRL, F, exec, $browser
bind = $mainMod CTRL, H, exec, $terminal "btop"

#--- BRIGHTNESS VOLUME CONTROL ---
binde= , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 2%+
binde= , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-
binde= , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

bind = , XF86MonBrightnessUp, exec, brightnessctl s +1%
bind = , XF86MonBrightnessDown, exec, brightnessctl s 1%-

# --- Focus ---
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

bind = $mainMod, h, movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d

bind = $mainMod, Tab, cyclenext

# --- Windows ---
bind = $mainMod, Q, killactive,

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bind = $mainMod SHIFT, left, movewindow, l
bind = $mainMod SHIFT, right, movewindow, r
bind = $mainMod SHIFT, up, movewindow, u
bind = $mainMod SHIFT, down, movewindow, d

bind = $mainMod SHIFT, h, movewindow, l
bind = $mainMod SHIFT, l, movewindow, r
bind = $mainMod SHIFT, k, movewindow, u
bind = $mainMod SHIFT, j, movewindow, d

bind = $mainMod, F, fullscreen, 2
bind = $mainMod SHIFT, F, togglefloating, B

# --- Workspaces ---
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

bind = $mainMod, mouse_up, workspace, -1
bind = $mainMod, mouse_down, workspace, +1

#закрепление, путешествует по воркспейсам
bind = $mainMod, P, pin 

# --- Screenshot ---
# monitor
bind = , Print, exec, hyprshot -m output -z --raw | swappy -f -
#  window
bind = $mainMod, Print, exec, hyprshot -m window -z --raw | swappy -f -
# Screenshot of the region
bind = $mainMod SHIFT, S, exec, hyprshot -m region -z --raw | swappy -f -

