input {
	repeat_delay = 200
	repeat_rate = 33
	kb_layout = $kb_layout
	kb_options = $kb_options
	follow_mouse = 1

	touchpad {
		natural_scroll = false
		scroll_factor = 0.1
		clickfinger_behavior = true
		drag_lock = true
	}
	
	numlock_by_default = true
	sensitivity = -0.2
}
