# --- resize
bind = $mainMod, R, submap, resize

# Start submap "resize"
submap = resize
# Sets repeatable binds for resizing the active window
binde = , right, resizeactive, 5 0
binde = , left, resizeactive, -5 0
binde = , up, resizeactive, 0 -5
binde = , down, resizeactive, 0 5
binde = , l, resizeactive, 5 0
binde = , h, resizeactive, -5 0
binde = , k, resizeactive, 0 -5
binde = , j, resizeactive, 0 5

# Use escape or R to go back to the global submap
bind = , escape, submap, reset
bind = , R, submap, reset

submap = reset



