#---------- НАСТРОЙКА МОНИТОРОВ ---- SETTING UP MONITORS
monitor=,preferred,auto,auto

#---------- ПЕРЕМЕННЫЕ ---- VARS
$mainMod = SUPER
$terminal = kitty
$filemanager = nemo
$browser = firefox

$kb_layout = us,ru
$kb_options = grp:alt_shift_toggle

#---------- АВТОЗАПУСК ---- AUTOSTART
source = /etc/ximperdistro/hyprland/hypr/system-autostart.conf
source = /etc/ximperdistro/hyprland/hypr/autostart.conf
source = /etc/ximperdistro/hyprland/hypr/xdg-autostart.conf

#source = /etc/ximperdistro/hyprland/hypr/plugins.conf

#---------- ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ ---- ENVIRONMENT VARIABLES
source = /etc/ximperdistro/hyprland/hypr/env.conf
#source = /etc/ximperdistro/hyprland/hypr/nvidia-env.conf

source = /etc/ximperdistro/hyprland/hypr/theme.conf

#---------- ПРОМЕЖУТКИ, ГРАНИЦЫ, ЦВЕТА ---- GAPS, BORDERS, COLORS
source = /etc/ximperdistro/hyprland/hypr/general.conf

#---------- УКРАШЕНИЯ ДЛЯ ОКОН ---- WINDOW DECORATIONS
source = /etc/ximperdistro/hyprland/hypr/decoration.conf

#---------- АНИМАЦИЯ ---- ANIMATION
source = /etc/ximperdistro/hyprland/hypr/animations.conf

#---------- РАСКЛАДКА КЛАВИАТУРЫ ---- KEYBOARD LAYOUT
#source = /etc/ximperdistro/hyprland/hypr/input.conf
source = /home/fantom/.config/hypr/incls/input.conf

#---------- ЖЕСТЫ ---- GESTURES
source = /home/fantom/.config/hypr/incls/gestures.conf

#---------- ГРУППЫ ---- GROUPS
source = /etc/ximperdistro/hyprland/hypr/groups.conf

#---------- РАЗНОЕ ---- MISC
source = /etc/ximperdistro/hyprland/hypr/misc.conf

#---------- ПРАВИЛА ---- RULES
source = /etc/ximperdistro/hyprland/hypr/rules.conf

#---------- СОЧЕТАНИЯ КЛАВИШ ---- KEYBOARD SHORTCUTS
#source = /etc/ximperdistro/hyprland/hypr/binds.conf
source = /home/fantom/.config/hypr/incls/binds.conf
source = /etc/ximperdistro/hyprland/hypr/special-workspace.conf
#source = /etc/ximperdistro/hyprland/hypr/submaps.conf
source = /home/fantom/.config/hypr/incls/submap.conf

#---------- ЭКОСИСТЕМА ---- ECOSYSTEM
source = /etc/ximperdistro/hyprland/hypr/ecosystem.conf

# Здесь был Ёжик <3
# There was a Hedgehog here <3
# 
#    ..::::::::.
#   :::::::::::::
#  /. `:::::::::::
# o__,_::::::::::'
